CREATE TABLE roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE departments (
    id INT PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE regions (
    id INT PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE municipalities (
    id INT PRIMARY KEY,
    department_id INT NOT NULL,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT fk_municipalities_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT uq_municipality UNIQUE KEY (department_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE communities (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    department_id INT NOT NULL,
    municipality_id INT NOT NULL,
    name VARCHAR(180) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_communities_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_communities_municipality FOREIGN KEY (municipality_id) REFERENCES municipalities(id),
    CONSTRAINT uq_community UNIQUE KEY (department_id, municipality_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE positions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    requires_department TINYINT(1) NOT NULL DEFAULT 0,
    requires_municipality TINYINT(1) NOT NULL DEFAULT 0,
    requires_slot TINYINT(1) NOT NULL DEFAULT 0,
    slot_min INT NULL,
    slot_max INT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT uq_position UNIQUE KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    role_id BIGINT UNSIGNED NOT NULL,
    department_id INT NULL,
    municipality_id INT NULL,
    community_id BIGINT UNSIGNED NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    verification_token VARCHAR(128) NULL,
    email_verified_at DATETIME NULL,
    last_login_at DATETIME NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_users_municipality FOREIGN KEY (municipality_id) REFERENCES municipalities(id),
    CONSTRAINT fk_users_community FOREIGN KEY (community_id) REFERENCES communities(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE password_reset_tokens (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    token VARCHAR(128) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE persons (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone_primary VARCHAR(30) NOT NULL,
    phone_secondary VARCHAR(30) NULL,
    birth_date DATE NOT NULL,
    profession VARCHAR(120) NOT NULL,
    dpi VARCHAR(13) NOT NULL UNIQUE,
    email VARCHAR(180) NULL,
    no_empadronamiento VARCHAR(3D0),
    centro_votacion VARCHAR(30),
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_persons_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE candidate_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    person_id BIGINT UNSIGNED NOT NULL UNIQUE,
    finiquito BOOLEAN NOT NULL DEFAULT FALSE,
    antecedente_penal BOOLEAN NOT NULL DEFAULT FALSE,
    antecedente_policial BOOLEAN NOT NULL DEFAULT FALSE,
    denuncia BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_candidate_profiles_person FOREIGN KEY (person_id) REFERENCES persons(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE leader_type(
    id INT PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE leader_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    person_id BIGINT UNSIGNED NOT NULL UNIQUE,
    finiquito BOOLEAN NOT NULL DEFAULT FALSE,
    antecedente_penal BOOLEAN NOT NULL DEFAULT FALSE,
    antecedente_policial BOOLEAN NOT NULL DEFAULT FALSE,
    denuncia BOOLEAN NOT NULL DEFAULT FALSE,
    department_id INT NOT NULL,
    region_id INT,
    leader_type_id INT NOT NULL,
    municipality_id INT NOT NULL,
    community_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_leader_profiles_type FOREIGN KEY (leader_type_id) REFERENCES leader_type(id);
    CONSTRAINT fk_leader_profiles_region FOREIGN KEY (region_id) REFERENCES regions(id),
    CONSTRAINT fk_leader_profiles_person FOREIGN KEY (person_id) REFERENCES persons(id),
    CONSTRAINT fk_leader_profiles_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_leader_profiles_municipality FOREIGN KEY (municipality_id) REFERENCES municipalities(id),
    CONSTRAINT fk_leader_profiles_community FOREIGN KEY (community_id) REFERENCES communities(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE affiliate_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    person_id BIGINT UNSIGNED NOT NULL UNIQUE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_affiliate_profiles_person FOREIGN KEY (person_id) REFERENCES persons(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE candidate_assignments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    candidate_profile_id BIGINT UNSIGNED NOT NULL UNIQUE,
    position_id BIGINT UNSIGNED NOT NULL,
    department_id INT NULL,
    municipality_id INT NULL,
    slot INT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    notes VARCHAR(255) NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_candidate_assignments_candidate FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profiles(id),
    CONSTRAINT fk_candidate_assignments_position FOREIGN KEY (position_id) REFERENCES positions(id),
    CONSTRAINT fk_candidate_assignments_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_candidate_assignments_municipality FOREIGN KEY (municipality_id) REFERENCES municipalities(id),
    CONSTRAINT fk_candidate_assignments_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE affiliate_assignments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    affiliate_profile_id BIGINT UNSIGNED NOT NULL UNIQUE,
    department_id INT NOT NULL,
    municipality_id INT NOT NULL,
    community_id BIGINT UNSIGNED NULL,
    leader_profile_id BIGINT UNSIGNED NULL,
    notes VARCHAR(255) NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_affiliate_assignments_affiliate FOREIGN KEY (affiliate_profile_id) REFERENCES affiliate_profiles(id),
    CONSTRAINT fk_affiliate_assignments_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_affiliate_assignments_municipality FOREIGN KEY (municipality_id) REFERENCES municipalities(id),
    CONSTRAINT fk_affiliate_assignments_community FOREIGN KEY (community_id) REFERENCES communities(id),
    CONSTRAINT fk_affiliate_assignments_leader FOREIGN KEY (leader_profile_id) REFERENCES leader_profiles(id),
    CONSTRAINT fk_affiliate_assignments_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NULL,
    module_name VARCHAR(100) NOT NULL,
    action_name VARCHAR(100) NOT NULL,
    record_id VARCHAR(100) NULL,
    payload_json JSON NULL,
    ip_address VARCHAR(45) NULL,
    created_at DATETIME NOT NULL,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO roles (name) VALUES
('ADMINISTRADOR'),
('DELEGADO MUNICIPAL'),
('DELEGADO DEPARTAMENTAL'),
('LIDER COMUNITARIO');

insert  into leader_type(id,name) values
(1,"LIDER-MICRO-REGION"),
(2,"LIDER MUNICIPAL"),
(3,"LIDER REGIONAL"),
(4,"LIDER DEPARTAMENTAL"),
(5,"LIDER NACIONAL");

INSERT INTO regions (id,name) VALUES
(1,'METROPOLITANA'),
(2,'NORTE'),
(3,'NORORIENTE'),
(4,'SURORIENTE'),
(5,'CENTRAL'),
(6,'SUROCCIDENTE'),
(7,'NOROCCIDENTE'),
(8,'PETEN');

INSERT INTO departments (id, name) VALUES
(1, 'Guatemala'),
(2, 'El Progreso'),
(3, 'Sacatepéquez'),
(4, 'Chimaltenango'),
(5, 'Escuintla'),
(6, 'Santa Rosa'),
(7, 'Sololá'),
(8, 'Totonicapán'),
(9, 'Quetzaltenango'),
(10, 'Suchitepéquez'),
(11, 'Retalhuleu'),
(12, 'San Marcos'),
(13, 'Huehuetenango'),
(14, 'El Quiché'),
(15, 'Baja Verapaz'),
(16, 'Alta Verapaz'),
(17, 'El Petén'),
(18, 'Izabal'),
(19, 'Zacapa'),
(20, 'Chiquimula'),
(21, 'Jalapa'),
(22, 'Jutiapa');

INSERT INTO municipalities (id, department_id, name) VALUES
(101, 1, 'Guatemala'),
(102, 1, 'Santa Catarina Pinula'),
(103, 1, 'San José Pinula'),
(104, 1, 'San José del Golfo'),
(105, 1, 'Palencia'),
(106, 1, 'Chinautla'),
(107, 1, 'San Pedro Ayampuc'),
(108, 1, 'Mixco'),
(109, 1, 'San Pedro Sacatepequez'),
(110, 1, 'San Juan Sacatepequez'),
(111, 1, 'San Raymundo'),
(112, 1, 'Chuarrancho'),
(113, 1, 'Fraijanes'),
(114, 1, 'Amatitlán'),
(115, 1, 'Villa Nueva'),
(116, 1, 'Villa Canales'),
(117, 1, 'San Miguel Petapa'),
(201, 2, 'Guastatoya'),
(202, 2, 'Morazán'),
(203, 2, 'San Agustín Acasaguastlan'),
(204, 2, 'San Cristóbal Acasaguastlan'),
(205, 2, 'El Jícaro'),
(206, 2, 'Sansare'),
(207, 2, 'Sanarate'),
(208, 2, 'San Antonio La Paz'),
(301, 3, 'Antigua Guatemala'),
(302, 3, 'Jocotenango'),
(303, 3, 'Pastores'),
(304, 3, 'Sumpango'),
(305, 3, 'Santo Domingo Xenacoj'),
(306, 3, 'Santiago Sacatepequez'),
(307, 3, 'San Bartolomé Milpas Altas'),
(308, 3, 'San Lucas Sacatepequez'),
(309, 3, 'Santa Lucía Milpas Altas'),
(310, 3, 'Magdalena Milpas Altas'),
(311, 3, 'Santa María de Jesús'),
(312, 3, 'Ciudad Vieja'),
(313, 3, 'San Miguel Dueñas'),
(314, 3, 'San Juan Alotenango'),
(315, 3, 'San Antonio Aguas Calientes'),
(316, 3, 'Santa Catarina Barahona'),
(4001, 4, 'Chimaltenango'),
(4002, 4, 'San José Poaquil'),
(4003, 4, 'San Martín Jilotepeque'),
(4004, 4, 'San Juan Comalapa'),
(4005, 4, 'Santa Apolonia'),
(4006, 4, 'Tecpán Guatemala'),
(4007, 4, 'Patzun'),
(4008, 4, 'San Miguel Pochuta'),
(4009, 4, 'Patzicia'),
(4010, 4, 'Santa Cruz Balanyá'),
(4011, 4, 'Acatenango'),
(4012, 4, 'San Pedro Yepocapa'),
(4013, 4, 'San Andrés Itzapa'),
(4014, 4, 'Parramos'),
(4015, 4, 'Zaragoza'),
(4016, 4, 'El Tejar'),
(501, 5, 'Escuintla'),
(502, 5, 'Santa Lucía Cotzumalguapa'),
(503, 5, 'La Democracia'),
(504, 5, 'Siquinalá'),
(505, 5, 'Masagua'),
(506, 5, 'Pueblo Nuevo Tiquisate'),
(507, 5, 'La Gomera'),
(508, 5, 'Guanagazapa'),
(509, 5, 'Puerto de San José'),
(510, 5, 'Iztapa'),
(511, 5, 'Palín'),
(512, 5, 'San Vicente Pacaya'),
(513, 5, 'Nueva Concepción'),
(601, 6, 'Cuilapa'),
(602, 6, 'Berberena'),
(603, 6, 'San Rosa de Lima'),
(604, 6, 'Casillas'),
(605, 6, 'San Rafael Las Flores'),
(606, 6, 'Oratorio'),
(607, 6, 'San Juan TEcuaco'),
(608, 6, 'Chiquimulilla'),
(609, 6, 'Taxisco'),
(610, 6, 'Santa María Ixhuatan'),
(611, 6, 'Guazacapán'),
(612, 6, 'Santa Cruz Naranjo'),
(613, 6, 'Pueblo Nuevo Viñas'),
(614, 6, 'Nueva Santa Rosa'),
(701, 7, 'Sololá'),
(702, 7, 'San José Chacaya'),
(703, 7, 'Santa María Visitación'),
(704, 7, 'Santa Lucía Utatlán'),
(705, 7, 'Nahualá'),
(706, 7, 'Santa Catarina Ixtahuacán'),
(707, 7, 'Santa Clara La Laguna'),
(708, 7, 'Concepción'),
(709, 7, 'San Andrés Semetabaj'),
(710, 7, 'Panajachel'),
(711, 7, 'Santa Catarina Palopó'),
(712, 7, 'San Antonio Palopó'),
(713, 7, 'San Lucas Tolimán'),
(714, 7, 'Santa Cruz La Laguna'),
(715, 7, 'Sna Pablo La Laguna'),
(716, 7, 'San Marcos La Laguna'),
(717, 7, 'San Juan La Laguna'),
(718, 7, 'San Pedro La Laguna'),
(719, 7, 'Santiago Atitlán'),
(801, 8, 'Totonicapán'),
(802, 8, 'San Cristóbal Totonicapán'),
(803, 8, 'San Francisco El Alto'),
(804, 8, 'San Andrés Xecul'),
(805, 8, 'Momostenango'),
(806, 8, 'Santa María Chiquimula'),
(807, 8, 'Santa Lucía La Reforma'),
(808, 8, 'San Bartolo Aguas Calientes'),
(901, 9, 'Quetzaltenango'),
(902, 9, 'Salcajá'),
(903, 9, 'Olintepeque'),
(904, 9, 'San Carlos Sija'),
(905, 9, 'Sibilia'),
(906, 9, 'Cabrican'),
(907, 9, 'Cajola'),
(908, 9, 'San Miguel Siguilça'),
(909, 9, 'San Juan Ostuncalco'),
(910, 9, 'San Mateo'),
(911, 9, 'Concepción Chiquirichapa'),
(912, 9, 'San Martín Sacatepequez'),
(913, 9, 'Almolonga'),
(914, 9, 'Cantel'),
(915, 9, 'Huitán'),
(916, 9, 'Zunil'),
(917, 9, 'Colomba'),
(918, 9, 'San Francisco La Unión'),
(919, 9, 'El Palmar'),
(920, 9, 'Coatepeque'),
(921, 9, 'Génova'),
(922, 9, 'Flores Costa Cuca'),
(923, 9, 'La Esperanza'),
(924, 9, 'Palestina de los Altos'),
(1001, 10, 'Mazatenango'),
(1002, 10, 'Cuyotenango'),
(1003, 10, 'San Francisco Zapotitlán'),
(1004, 10, 'San Bernardino'),
(1005, 10, 'San José El Ídolo'),
(1006, 10, 'Santo Domingo Suchitepequez'),
(1007, 10, 'San Lorenzo'),
(1008, 10, 'Samayac'),
(1009, 10, 'San Pablo Jocopilas'),
(1010, 10, 'San Antonio Suchitepéquez'),
(1011, 10, 'San Miguel Panán'),
(1012, 10, 'San Gabriel'),
(1013, 10, 'Chicacao'),
(1014, 10, 'Patulul'),
(1015, 10, 'Santa Bárbara'),
(1016, 10, 'San Juan Bautista'),
(1017, 10, 'Santo Tomás La Unión'),
(1018, 10, 'Zunilito'),
(1019, 10, 'Pueblo Nuevo Suchitepéquez'),
(1020, 10, 'Río Bravo'),
(1101, 11, 'Retalhuelu'),
(1102, 11, 'San Sebastián'),
(1103, 11, 'Santa Cruz Mulúa'),
(1104, 11, 'San Martín Zapotitlán'),
(1105, 11, 'San Felipe Retalhuleu'),
(1106, 11, 'San Andrés Villa Seca'),
(1107, 11, 'Champerico'),
(1108, 11, 'Nuevo San Carlos'),
(1109, 11, 'El Asintal'),
(1201, 12, 'San Marcos'),
(1202, 12, 'San Pedro Sacatepéquez'),
(1203, 12, 'Comitancillo'),
(1204, 12, 'San Antonio Sacatepéquez'),
(1205, 12, 'San Miguel Ixtahuacan'),
(1206, 12, 'Concepción Tutuapa'),
(1207, 12, 'Tacaná'),
(1208, 12, 'Sibinal'),
(1209, 12, 'Tajumulco'),
(1210, 12, 'Tejutla'),
(1211, 12, 'San Rafael Pié de la Cuesta'),
(1212, 12, 'Nuevo Progreso'),
(1213, 12, 'El Tumbador'),
(1214, 12, 'San José El Rodeo'),
(1215, 12, 'Malacatán'),
(1216, 12, 'Catarina'),
(1217, 12, 'Ayutla'),
(1218, 12, 'Ocos'),
(1219, 12, 'San Pablo'),
(1220, 12, 'El Quetzal'),
(1221, 12, 'La Reforma'),
(1222, 12, 'Pajapita'),
(1223, 12, 'Ixchiguan'),
(1224, 12, 'San José Ojetenán'),
(1225, 12, 'San Cristóbal Cucho'),
(1226, 12, 'Sipacapa'),
(1227, 12, 'Esquipulas Palo Gordo'),
(1228, 12, 'Río Blanco'),
(1229, 12, 'San Lorenzo'),
(1301, 13, 'Huehuetenango'),
(1302, 13, 'Chiantla'),
(1303, 13, 'Malacatancito'),
(1304, 13, 'Cuilco'),
(1305, 13, 'Nentón'),
(1306, 13, 'San Pedro Necta'),
(1307, 13, 'Jacaltenango'),
(1308, 13, 'San Pedro Soloma'),
(1309, 13, 'San Ildelfonso Ixtahuac´n'),
(1310, 13, 'Santa Bárbara'),
(1311, 13, 'La Libertad'),
(1312, 13, 'La Democracia'),
(1313, 13, 'San Miguel Acatán'),
(1314, 13, 'San Rafael La Independencia'),
(1315, 13, 'Todos Santos Chuchcumatán'),
(1316, 13, 'San Juan Atitán'),
(1317, 13, 'Santa Eulalia'),
(1318, 13, 'San Mateo Ixtatán'),
(1319, 13, 'Colotenango'),
(1320, 13, 'San Sebastián Huehuetenango'),
(1321, 13, 'Tectitán'),
(1322, 13, 'Concepción Huista'),
(1323, 13, 'San Juan Ixcoy'),
(1324, 13, 'San Antonio Huista'),
(1325, 13, 'San Sebastián Coatán'),
(1326, 13, 'Santa Cruz Barillas'),
(1327, 13, 'Aguacatán'),
(1328, 13, 'San Rafael Petzal'),
(1329, 13, 'San Gaspar Ixchil'),
(1330, 13, 'Santiago Chimaltenango'),
(1331, 13, 'Santa Ana Huista'),
(1401, 14, 'Santa Cruz del Quiche'),
(1402, 14, 'Chiche'),
(1403, 14, 'Chinique'),
(1404, 14, 'Zacualpa'),
(1405, 14, 'Chajul'),
(1406, 14, 'Santo Tomás Chichicstenango'),
(1407, 14, 'Patzité'),
(1408, 14, 'San Antonio Ilotenango'),
(1409, 14, 'San Pedro Jocopilas'),
(1410, 14, 'Cunén'),
(1411, 14, 'San Juan Cotzal'),
(1412, 14, 'Joyabaj'),
(1413, 14, 'Santa María Nebaj'),
(1414, 14, 'San Andrés Sajcabajá'),
(1415, 14, 'San Miguel Uspatán'),
(1416, 14, 'Sacapulas'),
(1417, 14, 'San Bartolomé Jocotenango'),
(1418, 14, 'Canilla'),
(1419, 14, 'Chicaman'),
(1420, 14, 'Playa Grnade - Ixcán'),
(1421, 14, 'Pachalúm'),
(1501, 15, 'Salamá'),
(1502, 15, 'San Miguel Chicaj'),
(1503, 15, 'Rabinal'),
(1504, 15, 'Cubulco'),
(1505, 15, 'Granados'),
(1506, 15, 'Santa Cruz El Chol'),
(1507, 15, 'San Jerónimo'),
(1508, 15, 'Purulhá'),
(1601, 16, 'Cobán'),
(1602, 16, 'Santa Cruz Verapaz'),
(1603, 16, 'San Cristobal Verapaz'),
(1604, 16, 'Tactíc'),
(1605, 16, 'Tamahú'),
(1606, 16, 'San Miguel Tucurú'),
(1607, 16, 'Panzos'),
(1608, 16, 'Senahú'),
(1609, 16, 'San Pedro Carchá'),
(1610, 16, 'SanJuan Chamelco'),
(1611, 16, 'Lanquín'),
(1612, 16, 'Santa María Cahabón'),
(1613, 16, 'Chisec'),
(1614, 16, 'Chahal'),
(1615, 16, 'Fray Bartolomé de las Casas'),
(1616, 16, 'Santa Catarina La Tinta'),
(1701, 17, 'Flores'),
(1702, 17, 'San José'),
(1703, 17, 'San Benito'),
(1704, 17, 'San Andrés'),
(1705, 17, 'La Libertad'),
(1706, 17, 'San Francisco'),
(1707, 17, 'Santa Ana'),
(1708, 17, 'Dolores'),
(1709, 17, 'San Luis'),
(1710, 17, 'Sayaxche'),
(1711, 17, 'Melchor de Mencos'),
(1712, 17, 'Poptún'),
(1801, 18, 'Puerto Barrios'),
(1802, 18, 'Livingston'),
(1803, 18, 'El Estor'),
(1804, 18, 'Morales'),
(1805, 18, 'Los Amates'),
(1901, 19, 'Zacapa'),
(1902, 19, 'Estanzuela'),
(1903, 19, 'Río Hondo'),
(1904, 19, 'gualán'),
(1905, 19, 'Teculután'),
(1906, 19, 'Usumatlán'),
(1907, 19, 'Cabañas'),
(1908, 19, 'San Diego'),
(1909, 19, 'La Unión'),
(1910, 19, 'Huite'),
(2001, 20, 'Chiquimula'),
(2002, 20, 'San José La Arada'),
(2003, 20, 'San Juan Hermita'),
(2004, 20, 'Jocotán'),
(2005, 20, 'Camotán'),
(2006, 20, 'Olopa'),
(2007, 20, 'Esquipulas'),
(2008, 20, 'Concepción Las Minas'),
(2009, 20, 'Quezaltepeque'),
(2010, 20, 'San Jacinto'),
(2011, 20, 'Ipala'),
(2101, 21, 'Jalapa'),
(2102, 21, 'San Pedro Pinula'),
(2103, 21, 'San Luis Jilotepeque'),
(2104, 21, 'San Manuel Chaparrón'),
(2105, 21, 'San Carlos Alzatate'),
(2106, 21, 'Monjas'),
(2107, 21, 'Mataquescuintla'),
(2201, 22, 'Jutiapa'),
(2202, 22, 'El Progreso'),
(2203, 22, 'Santa Catarina Mita'),
(2204, 22, 'Agua Blanca'),
(2205, 22, 'Asunción Mita'),
(2206, 22, 'Yupiltepeque'),
(2207, 22, 'Atescatempa'),
(2208, 22, 'Jerez'),
(2209, 22, 'El Adelanto'),
(2210, 22, 'Zapotitlán'),
(2211, 22, 'Comapa'),
(2212, 22, 'Jalpatagua'),
(2213, 22, 'Conguaco'),
(2214, 22, 'Moyuta'),
(2215, 22, 'Pasaco'),
(2216, 22, 'San José Acatempa'),
(2217, 22, 'Quezada');

INSERT INTO positions (name, requires_department, requires_municipality, requires_slot, slot_min, slot_max, is_active, created_at, updated_at) VALUES
('Diputado listado nacional', 0, 0, 1, 1, 10, 1, NOW(), NOW()),
('Diputado parlacen', 0, 0, 1, 1, 10, 1, NOW(), NOW()),
('Diputado departamental distrital', 1, 0, 1, 1, 10, 1, NOW(), NOW()),
('Alcalde municipal', 1, 1, 0, NULL, NULL, 1, NOW(), NOW()),
('Síndico de I a V', 1, 1, 0, NULL, NULL, 1, NOW(), NOW()),
('Concejal de I a X', 1, 1, 0, NULL, NULL, 1, NOW(), NOW());
